version: '3.9'
services: 

wordpress_app:
    image: wordpress:4.9.4-php7.2-apache
    container_name: wordpress_web
    environment: 
      -   WORDPRESS_DB_HOST=root
      -   WORDPRESS_DB_USER=adedb_user
      -   WORDPRESS_DB_PASSWORD=hello123
      -   WORDPRESS_DB_NAME=wordpress_db
    ports:
      - 8080:80
    volumes:
      - wordpress_app:/var/www/html
    networks:
      - my_netwk_wdpress

volumes:
  wordpress_app:
networks: 'bridge'

  