apiVersion: v1
kind: Service 
metadata:
  name: wordpress-svc
spec:
  selector: # select the pod using the labels of pods.
      app: wordpress-app
  type: NodePort 
  ports:
    - protocol: TCP
      port:  80
      targetPort: 80 # port in the pod where the application is running
      nodePort: 30080 # port that expose the service to the nodes