apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql-db
  name: mysql-pod
spec:
  containers:
  - image: mysql:8.0
    name: mysql-container
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_DATABASE
        valueFrom:  # name of the service
          configMapKeyRef:
            key: WORDPRESS_DB_NAME
            name: wordpress-cm

        name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            key: WORDPRESS_DB_USER
            name: app-secret

        name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            key: WORDPRESS_DB_PASSWORD
            name: app-secret
    volumeMounts:
      - mountPath: /var/lib/mysql
        name: data-volume

  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: mysql-pvc


