apiVersion: v1
kind: Service
metadata: 
  name: nginx_deploy_service

spec: 
  type: NodePort
  ports: 
    - port: 80        #this is the port of my service
      targetPort: 80  #this is the port of my container
      nodePort: 30182 #this is the port of my wokr node
  selector: 
    app: my-web-app   #this is the name container label
    tier: frontend    #this is also the name of the container label
    