apiVersion: apps/v1
kind: Deployment 
metadata:
  name: my-web-deployment
  labels:
    app: my-web

spec:
 selector:
  matchLabels:
    app: my-web-app
    tier: frontend
 template:
  metadata:
    name: my-webserver
    labels:
      app: my-web-app
      tier: frontend
  spec:
    containers:
    - name: c1
      image: nginx:1.27.3-alpine
      ports:
      - containerPort: 80
 replicas: 6