apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql-app
  name: mysql
spec:
  containers:
  - image: mysql:8.0.32
    name: mysql
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: db_password
          name: secret-wordpress

    - name: MYSQL_DATABASE
      valueFrom:
        ConfigMapKeyRef:
          key: db_name
          name: config-wordpress 