apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
  name: wordpress-container
spec:
  containers:
  - env:
    - name: WORDPRESS_DB_HOST
      value: "mysql-db"
    - name: WORDPRESS_DB_PASSWORD
      value: xxxx
    image: wordpress:4.8-apache
    name: wordpress-container
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}