apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wordpress
  name: wordpress-container
spec:
  containers:
  - env:
    - name: WORDPRESS_DB_HOST
      ValueFrom: 
        configMapKeyRef:
          name: config-worpdress
          key: data_host 
    - name: WORDPRESS_DB_PASSWORD
      value: hello123
