apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
        - name: wordpress-container
          image: wordpress:5.8.3-php7.4-apache
          ports:
            - containerPort: 80
              name: wordpress-port
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-host
            - name: WORDPRESS_DB_USER
              value: Adelina
            - name: WORDPRESS_DB_PASSWORD
              value: wordpress-password
            - name: WORDPRESS_DB_NAME
              value: wordpress-db
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-volume

      volumes:
            - name: 
              hostPath:
                path: /data
              



      



